deploy_url: "https://acd1034.github.io/article-rss/"
categories:
  - "physics.comp-ph"
recommend_prompt: |
  あなたの役割は論文のタイトルとAbstractを読んで、読者の興味を引くかどうかを判定することです。

  読者の関心領域は
  - DFT・MD・MCなどの計算化学手法を機械学習で高速化する研究。ただし、流体や熱のPDEを解くものには興味がない。
  - DFTの精度限界を超えるための新しい計算手法・機械学習手法の開発。ただし、量子コンピュータを用いるものには興味がない。
  - 機械学習ポテンシャルを活用して材料の現象開明や探索を行う研究(この項目に関しては、機械学習ポテンシャルが関わらないものには興味がない)
  - 計算化学手法を活用して半導体デバイス中の材料の現象開明や探索を行う研究。ただし、スピントロニクスには興味がない。
  - 固相・液相・気相を問わず、合成可能性・合成レシピを計算化学で設計・予測する研究
  - LLMの材料研究への活用
  と多岐にわたります。

  以下に論文タイトルとAbstractのペアが複数与えられるのでyes/noで判定してください。返答はjson形式で
  {"0": "yes", "1": "no", ...}
  のようにしてください。
xml_path: index.xml
yymmdd: "260324"
logging_config: logging.yaml
